Add Undeploy
blackducksoftware/horizon pull request #10
Opened 2018-08-05 14:56 UTC by jdartigalongue

2018-08-05 14:56 UTC, jdartigalongue commented
@rrati

2018-08-06 17:06 UTC, rrati requested changes

2018-08-06 17:06 UTC, rrati commented on pkg/deployer/deployer.go
> +func (d *Deployer) Undeploy() error {
The order here is important.  Deleting the namespace will delete all the components in the namespace which could cause errors later in the undeploy.  We should probably look at this deploy/undeploy and find a way to more logically group them.  For now, I would have the undeploy do the operations in the opposite order as the deploy.

2018-08-06 17:06 UTC, rrati commented on pkg/deployer/deployer.go
> +		cm, err := converters.Convert_Koki_ConfigMap_to_Kube_v1_ConfigMap(wrapper)
I would rather us add a GetNamespace method to the component structs than do this conversion all the time on delete.  The information is easily obtainable in the component structs, but it just isn't exposed atm.  Much less costly to add the methods rather than do these conversions.

2018-08-07 21:36 UTC, jdartigalongue commented
@rrati I have updated the order in Undeploy and removed the unnecessary component conversion.

2018-08-08 12:37 UTC, rrati approved these changes
lgtm

2018-08-08 12:38 UTC, merged